//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheR7angelo.github.io.Resources.Resx.DatabaseSection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatabaseSectionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseSectionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheR7angelo.github.io.Resources.Resx.DatabaseSection.DatabaseSectionResources", typeof(DatabaseSectionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted queries, materialized views to lighten the load, and accurate typing (VARCHAR throttling) to save memory..
        /// </summary>
        internal static string ArchitectureSchematicsContent {
            get {
                return ResourceManager.GetString("ArchitectureSchematicsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Architecture &amp; Schematics:.
        /// </summary>
        internal static string ArchitectureSchematicsHeader {
            get {
                return ResourceManager.GetString("ArchitectureSchematicsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow query diagnostics, shrink/reindex for size, automated backups, and granular (line-by-line) restore..
        /// </summary>
        internal static string MaintenanceOperationContent {
            get {
                return ResourceManager.GetString("MaintenanceOperationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance &amp; Operations:.
        /// </summary>
        internal static string MaintenanceOperationHeader {
            get {
                return ResourceManager.GetString("MaintenanceOperationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💡 My vision.
        /// </summary>
        internal static string MyVision {
            get {
                return ResourceManager.GetString("MyVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgical indexation on clauses.
        /// </summary>
        internal static string PerformanceAutomationContent1 {
            get {
                return ResourceManager.GetString("PerformanceAutomationContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , triggers to avoid redundancies, and asynchronous stat aggregation (pg_cron)..
        /// </summary>
        internal static string PerformanceAutomationContent2 {
            get {
                return ResourceManager.GetString("PerformanceAutomationContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance &amp; Automation:.
        /// </summary>
        internal static string PerformanceAutomationHeader {
            get {
                return ResourceManager.GetString("PerformanceAutomationHeader", resourceCulture);
            }
        }
    }
}
